/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tema_2;

import javax.swing.JOptionPane;
import Libsss.calcula_si_num_es_primo;
/**
 *
 * @author noama
 */
public class numeros_primos_1 extends javax.swing.JFrame {

    /**
     * Creates new form numeros_primos_1
     */
    public numeros_primos_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_numeros = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Números Primos");

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese un número entero positivo de cuatro digitos:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numerosActionPerformed(evt);
            }
        });
        txt_numeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numerosKeyTyped(evt);
            }
        });
        jPanel1.add(txt_numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, -1));

        jButton1.setText("Determinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txt_numeros.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese un numero entero positivo por favor.", "Error", JOptionPane.ERROR_MESSAGE);
            txt_numeros.requestFocus();
        }else{
            int valor = 0;
            String menssage = "";
            valor = Integer.parseInt(txt_numeros.getText());
            calcula_si_num_es_primo obj = new calcula_si_num_es_primo();
            menssage = ""+ obj.Primo(valor);
            JOptionPane.showMessageDialog(null, "El numero "+ valor + " "+ menssage+".", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
            txt_numeros.setText("");
            txt_numeros.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_numerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numerosActionPerformed

    private void txt_numerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numerosKeyTyped
        if(txt_numeros.getText().length()>=4){
            evt.consume();
        }else{
            int key = evt.getKeyChar();
            boolean numeros = key >= 48 && key <=57;
            if(!numeros){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_numerosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(numeros_primos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(numeros_primos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(numeros_primos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(numeros_primos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numeros_primos_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_numeros;
    // End of variables declaration//GEN-END:variables
}
